import mat4 from './mat4';
export default class vec4 {
    x: number;
    y: number;
    z: number;
    w: number;
    xy: [number, number];
    xyz: [number, number, number];
    xyzw: [number, number, number, number];
    r: number;
    g: number;
    b: number;
    a: number;
    rg: [number, number];
    rgb: [number, number, number];
    rgba: [number, number, number, number];
    constructor(values?: [number, number, number, number]);
    private values;
    static readonly zero: vec4;
    static readonly one: vec4;
    at(index: number): number;
    reset(): void;
    copy(dest?: vec4): vec4;
    negate(dest?: vec4): vec4;
    equals(vector: vec4, threshold?: number): boolean;
    length(): number;
    squaredLength(): number;
    add(vector: vec4): vec4;
    subtract(vector: vec4): vec4;
    multiply(vector: vec4): vec4;
    divide(vector: vec4): vec4;
    scale(value: number, dest?: vec4): vec4;
    normalize(dest?: vec4): vec4;
    multiplyMat4(matrix: mat4, dest?: vec4): vec4;
    static mix(vector: vec4, vector2: vec4, time: number, dest?: vec4): vec4;
    static sum(vector: vec4, vector2: vec4, dest?: vec4): vec4;
    static difference(vector: vec4, vector2: vec4, dest?: vec4): vec4;
    static product(vector: vec4, vector2: vec4, dest?: vec4): vec4;
    static quotient(vector: vec4, vector2: vec4, dest?: vec4): vec4;
}
